import { jsPDF } from 'jspdf';

// ──────────────────────────────────────────
// Generate Trust Capsule PDF (Upgraded)
// ──────────────────────────────────────────
export function downloadTrustCapsule({ trustScore, results, timestamp }) {
  const doc = new jsPDF({ format: 'a4', unit: 'pt' });
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Colors
  const primary = [14, 165, 233];
  const danger = [220, 38, 38];
  const success = [22, 163, 74];
  const warning = [202, 138, 4];
  
  const riskColor = 
    trustScore.risk_level === 'Critical' ? danger :
    trustScore.risk_level === 'High' ? warning :
    trustScore.risk_level === 'Medium' ? warning : success;

  // Header Background
  doc.setFillColor(15, 23, 42); // Navy
  doc.rect(0, 0, pageWidth, 120, 'F');

  // Title / Logo
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('ShadowGuard AI', 40, 55);
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(148, 163, 184);
  doc.text('OFFICIAL TRUST CAPSULE', 40, 75);
  doc.text(`ID: SG-${Math.random().toString(36).substr(2, 9).toUpperCase()}`, 40, 90);

  // QR Code Placeholder (Draw a box representing QR)
  doc.setFillColor(255, 255, 255);
  doc.rect(pageWidth - 100, 30, 60, 60, 'F');
  doc.setFontSize(8);
  doc.setTextColor(15, 23, 42);
  doc.text('VERIFY', pageWidth - 90, 60);

  // Score Dashboard Section
  doc.setDrawColor(226, 232, 240);
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(40, 150, pageWidth - 80, 140, 8, 8, 'FD');

  // Trust Score Circular Graphic (simulated with text)
  doc.setFontSize(14);
  doc.setTextColor(100, 116, 139);
  doc.text('TRUST SCORE', 70, 190);
  doc.setFontSize(48);
  doc.setTextColor(riskColor[0], riskColor[1], riskColor[2]);
  doc.setFont('helvetica', 'bold');
  doc.text(`${trustScore.trust_score}`, 70, 235);
  doc.setFontSize(18);
  doc.text('/100', 135, 235);

  // Risk Badge & Info
  doc.setFontSize(14);
  doc.setTextColor(riskColor[0], riskColor[1], riskColor[2]);
  doc.text(`${trustScore.risk_level.toUpperCase()} RISK DETECTED`, 220, 190);
  
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.setFont('helvetica', 'normal');
  doc.text(`Date & Time: ${timestamp || new Date().toLocaleString()}`, 220, 215);

  // Recommendation Card
  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(...riskColor);
  doc.setLineWidth(1.5);
  doc.roundedRect(40, 310, pageWidth - 80, 70, 6, 6, 'FD');
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text('AI RECOMMENDATION:', 55, 335);
  doc.setFont('helvetica', 'normal');
  doc.text(trustScore.recommendation, 55, 355, { maxWidth: pageWidth - 110 });

  // Detailed Evidence Breakdown
  let y = 420;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text('Evidence & Artifact Analysis', 40, y);
  
  y += 30;

  Object.entries(results).forEach(([module, result]) => {
    if (!result) return;
    
    // Module Card
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(1);
    doc.setFillColor(255, 255, 255);
    doc.roundedRect(40, y, pageWidth - 80, 90, 6, 6, 'FD');
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    doc.text(`${module.toUpperCase()} SHIELD`, 55, y + 25);
    
    const mColor = result.status === 'Safe' ? success : danger;
    doc.setTextColor(mColor[0], mColor[1], mColor[2]);
    doc.text(`${result.score}% Authentic`, pageWidth - 140, y + 25);

    // Reasons
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    
    let ry = y + 45;
    result.reasons.forEach(r => {
      doc.text(`• ${r}`, 55, ry);
      ry += 15;
    });

    y += 110;
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text('This report was generated by ShadowGuard AI. Results are probabilistic and should be verified.', 40, doc.internal.pageSize.getHeight() - 40);

  doc.save(`ShadowGuard_TrustCapsule_${Date.now()}.pdf`);
}
